### ISSUE TITLE
Rest Pose A missing from UI

### ISSUE THREAD

**Issue by NickTiny** [NickTiny/blender-rhubarb-lipsync#7]
I can't believe I missed this in all of the tutorial documentation and everything! Will add it back asap!

**Comment by NickTiny** [comment]
Closed by https://github.com/NickTiny/blender-rhubarb-2d-lipsync/pull/8

**Comment by silkef** [comment]
Hi, thank you so much for this addon. I've tried it in blender 4.2 but the fix doesn't work in 4.2 Is there a way to fix it? I really would like to use it in my project. 
![grafik](https://github.com/user-attachments/assets/83ddadb6-201c-4961-afe0-0677cde5cc8c)
