### ISSUE TITLE
Error!!! Json Decoder

### ISSUE THREAD

**Issue by Tracart** [NickTiny/blender-rhubarb-lipsync#9]
When click the button "Rhubarb lipsync" in Blender I get the following error message "Error!!! Json Decoder". Any ideas if I am doing something incorrect?

**Comment by GuillaumeGTHB** [comment]
Same for me...

**Comment by NickTiny** [comment]
Hello @ctrackim and @GuillaumeGTHB,

In my testing this error message comes up when the sound file is encoded incorrectly, or the specific codec/container isn't supported by [rhubarb](https://github.com/DanielSWolf/rhubarb-lip-sync#:~:text=Supported%20file%20formats%20are%20WAVE%20(.wav)%20and%20Ogg%20Vorbis%20(.ogg).). You can use the test files linked in the readme to test the application is working correctly on your machine. 

This `Error!!! Json Decoder` comes from the source project that I forked, so this is a good opportunity to improve it.

To make this simpler, I have have already merged a new PR to improve error messages and to [catch bad sound files](https://github.com/NickTiny/blender-rhubarb-2d-lipsync/pull/10) in this latest release https://github.com/NickTiny/blender-rhubarb-2d-lipsync/releases/tag/v4.0.2 so if your sound file is incorrect the application should clearly tell you that.

Can you try this new version out and let me know if it fixes your issue?

**Comment by AlesJelovcan** [comment]
In my case this error showed when trying to work with MP3. Changing to WAV solved it.
